apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "15"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"14"},"creationTimestamp":"2024-09-18T07:28:54Z","generation":39,"labels":{"app":"synergychat-api"},"name":"synergychat-api","namespace":"default","resourceVersion":"28399","uid":"bf05ce6c-8409-4430-bdfa-952d207b8aaf"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"synergychat-api"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"2024-09-19T08:53:21Z"},"creationTimestamp":null,"labels":{"app":"synergychat-api"}},"spec":{"containers":[{"env":[{"name":"API_PORT","valueFrom":{"configMapKeyRef":{"key":"API_PORT","name":"synergychat-api-configmap"}}},{"name":"API_DB_FILEPATH","valueFrom":{"configMapKeyRef":{"key":"API_DB_FILEPATH","name":"synergychat-api-configmap"}}}],"image":"bootdotdev/synergychat-api:latest","imagePullPolicy":"Always","name":"synergychat-api","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/persist","name":"synergychat-api-volume"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"name":"synergychat-api-volume","persistentVolumeClaim":{"claimName":"synergychat-api-pvc"}}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2024-09-19T08:59:48Z","lastUpdateTime":"2024-09-19T08:59:48Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2024-09-18T07:28:54Z","lastUpdateTime":"2024-09-19T08:59:48Z","message":"ReplicaSet \"synergychat-api-7fc65bb8db\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":39,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2024-09-18T07:28:54Z"
  generation: 44
  labels:
    app: synergychat-api
  name: synergychat-api
  namespace: default
  resourceVersion: "29797"
  uid: bf05ce6c-8409-4430-bdfa-952d207b8aaf
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: synergychat-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-09-19T08:53:21Z"
      creationTimestamp: null
      labels:
        app: synergychat-api
    spec:
      containers:
      - env:
        - name: API_PORT
          valueFrom:
            configMapKeyRef:
              key: API_PORT
              name: synergychat-api-configmap
        - name: API_DB_FILEPATH
          valueFrom:
            configMapKeyRef:
              key: API_DB_FILEPATH
              name: synergychat-api-configmap
        - name: CRAWLER_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: CRAWLER_BASE_URL
              name: synergychat-api-configmap
        image: bootdotdev/synergychat-api:latest
        imagePullPolicy: Always
        name: synergychat-api
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /persist
          name: synergychat-api-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: synergychat-api-volume
        persistentVolumeClaim:
          claimName: synergychat-api-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-09-18T07:28:54Z"
    lastUpdateTime: "2024-09-19T09:09:30Z"
    message: ReplicaSet "synergychat-api-7f495fb6ff" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-09-19T09:22:08Z"
    lastUpdateTime: "2024-09-19T09:22:08Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 44
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
