apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2024-09-19T10:16:50Z","generation":5,"labels":{"app":"synergychat-testcpu"},"name":"synergychat-testcpu","namespace":"default","resourceVersion":"36536","uid":"a5f35c2a-fac4-4095-a612-0562a3365de0"},"spec":{"progressDeadlineSeconds":600,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"synergychat-testcpu"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"synergychat-testcpu"}},"spec":{"containers":[{"image":"bootdotdev/synergychat-testcpu:latest","imagePullPolicy":"Always","name":"synergychat-testcpu","resources":{"limits":{"cpu":"50m"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"conditions":[{"lastTransitionTime":"2024-09-19T10:16:50Z","lastUpdateTime":"2024-09-19T10:16:55Z","message":"ReplicaSet \"synergychat-testcpu-6f6c76b646\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2024-09-19T11:06:28Z","lastUpdateTime":"2024-09-19T11:06:28Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":5}}
  creationTimestamp: "2024-09-19T10:16:50Z"
  generation: 10
  labels:
    app: synergychat-testcpu
  name: synergychat-testcpu
  namespace: default
  resourceVersion: "37811"
  uid: a5f35c2a-fac4-4095-a612-0562a3365de0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: synergychat-testcpu
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: synergychat-testcpu
    spec:
      containers:
      - image: bootdotdev/synergychat-testcpu:latest
        imagePullPolicy: Always
        name: synergychat-testcpu
        resources:
          limits:
            cpu: 10m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-09-19T10:16:50Z"
    lastUpdateTime: "2024-09-19T10:16:55Z"
    message: ReplicaSet "synergychat-testcpu-6f6c76b646" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-09-19T11:28:31Z"
    lastUpdateTime: "2024-09-19T11:28:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 10
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
